export type TenderDifficulty="EASY"|"MEDIUM"|"HARD"|"ELITE";
export interface TenderSpec{damage:number;accuracy:number;mobility:number;reliability:number}
export interface Tender{
 id:string;code:string;title:string;client:string;lore:string;weaponType:string;caliber:string;spec:TenderSpec;requirements:string[];reward:number;advance:number;penalty:number;durationHours:number;risk:string;difficulty:TenderDifficulty;linkedMission:string;
}
export const TENDERS:Tender[]=[
{id:"storm_rust",code:"R-17",title:"Операция «Ржавый рубеж»",client:"ЧВК «Шторм»",lore:"После серии сорванных контрактов «Шторм» собирает новый мобильный отряд. Нужен единый стандарт стрелкового вооружения без лишней экзотики.",weaponType:"Штурмовая винтовка",caliber:"5.56×45 мм",spec:{damage:72,accuracy:78,mobility:74,reliability:86},requirements:["унифицированная платформа","совместимый оптический интерфейс","устойчивость к интенсивной эксплуатации"],reward:1850,advance:500,penalty:650,durationHours:48,risk:"Перехват груза конкурентами и проверка происхождения партии.",difficulty:"MEDIUM",linkedMission:"valenti_04"},
{id:"nightglass",code:"N-04",title:"Контракт «Ночное стекло»",client:"Частная охранная группа «Меридиан»",lore:"Группа работает в плотной городской застройке и требует компактное оружие для патрульных групп.",weaponType:"Компактный карабин",caliber:"5.56×45 мм",spec:{damage:66,accuracy:82,mobility:88,reliability:80},requirements:["короткая конфигурация","низкая масса","модульный интерфейс"],reward:1600,advance:420,penalty:560,durationHours:36,risk:"Проверка на контрафактные комплектующие.",difficulty:"MEDIUM",linkedMission:"moretti_03"},
{id:"blackwaterline",code:"B-21",title:"Контракт «Чёрная линия»",client:"Группа «Северный порт»",lore:"Ночью пропали две партии оборудования. Заказчик меняет требования: груз должен быть компактным и устойчивым к грубой транспортировке.",weaponType:"Пистолет-пулемёт",caliber:"9×19 мм",spec:{damage:54,accuracy:68,mobility:94,reliability:84},requirements:["компактность","высокая мобильность","быстрая смена магазина"],reward:1320,advance:360,penalty:480,durationHours:30,risk:"Засада на маршруте и потеря части груза.",difficulty:"MEDIUM",linkedMission:"rossi_02"},
{id:"ironroute",code:"I-31",title:"Контракт «Железный маршрут»",client:"Логистический синдикат «Транзит»",lore:"Синдикат восстанавливает старый маршрут через промышленный район. Требуется надёжное оружие сопровождения.",weaponType:"Карабин",caliber:"7.62×39 мм",spec:{damage:84,accuracy:70,mobility:62,reliability:92},requirements:["высокая надёжность","простое обслуживание","устойчивость к загрязнению"],reward:2100,advance:600,penalty:780,durationHours:60,risk:"Блокирование маршрута и повреждение транспортной колонны.",difficulty:"HARD",linkedMission:"bellini_06"},
{id:"silent_district",code:"S-09",title:"Контракт «Тихий квартал»",client:"Корпоративная служба «Атлас»",lore:"Заказчику нужна малозаметная экипировка для вымышленной игровой операции наблюдения в городе.",weaponType:"Компактный пистолет",caliber:"9×19 мм",spec:{damage:48,accuracy:86,mobility:96,reliability:78},requirements:["скрытое ношение","низкая масса","стабильная точность"],reward:1180,advance:300,penalty:420,durationHours:24,risk:"Обнаружение наблюдательной группы.",difficulty:"EASY",linkedMission:"valenti_02"},
{id:"old_guard",code:"G-44",title:"Тендер «Старая гвардия»",client:"Охранная компания «Бастион»",lore:"«Бастион» заменяет устаревший парк оружия, но сохраняет приоритет надёжности и простоты эксплуатации.",weaponType:"Служебный пистолет",caliber:"9×19 мм",spec:{damage:58,accuracy:76,mobility:82,reliability:90},requirements:["простая эксплуатация","надёжность","единый тип боеприпаса"],reward:980,advance:240,penalty:320,durationHours:20,risk:"Конкурирующая заявка с демпингом.",difficulty:"EASY",linkedMission:"moretti_02"},
{id:"redarchive",code:"A-77",title:"Тендер «Красный архив»",client:"Закрытая аналитическая сеть «Архив»",lore:"Сеть формирует защищённую группу сопровождения для поиска потерянных документов.",weaponType:"Марксманский карабин",caliber:"7.62×51 мм",spec:{damage:92,accuracy:94,mobility:42,reliability:82},requirements:["высокая точность","стабильная оптика","контроль отдачи"],reward:2800,advance:800,penalty:1100,durationHours:72,risk:"Контрнаблюдение и потеря маршрута.",difficulty:"HARD",linkedMission:"rossi_08"},
{id:"fourfamilies",code:"F-13",title:"Контракт «Четыре печати»",client:"Совместный совет четырёх семей",lore:"После серии взаимных конфликтов стороны заключают временное соглашение. Нужна смешанная поставка для последней операции главы.",weaponType:"Смешанный оружейный комплект",caliber:"5.56×45 / 9×19 мм",spec:{damage:80,accuracy:84,mobility:76,reliability:88},requirements:["единый стандарт учёта","смешанная комплектация","полная проверка партии"],reward:4200,advance:1200,penalty:1800,durationHours:96,risk:"Срыв сделки одной из сторон и потеря доверия.",difficulty:"ELITE",linkedMission:"joint_13"}
];
export function tenderById(id:string){return TENDERS.find(t=>t.id===id)||null;}
export function difficultyRu(d:TenderDifficulty){return ({EASY:"НИЗКИЙ",MEDIUM:"СРЕДНИЙ",HARD:"ВЫСОКИЙ",ELITE:"ЭЛИТНЫЙ"} as Record<TenderDifficulty,string>)[d];}
