export type TenderDifficulty="EASY"|"MEDIUM"|"HARD"|"ELITE";
export interface TenderSpec{damage:number;accuracy:number;mobility:number;reliability:number}
export interface Tender{
 id:string;code:string;title:string;client:string;lore:string;weaponType:string;caliber:string;spec:TenderSpec;requirements:string[];reward:number;advance:number;penalty:number;durationHours:number;risk:string;difficulty:TenderDifficulty;linkedMission:string;
}
export const TENDERS:Tender[]=[
{id:"storm_rust",code:"R-17",title:"Операция «Ржавый рубеж»",client:"ЧВК «Шторм»",lore:"После серии сорванных контрактов «Шторм» собирает новый мобильный отряд. Нужен единый стандарт стрелкового вооружения без лишней экзотики.",weaponType:"Штурмовая винтовка",caliber:"5.56×45 мм",spec:{damage:72,accuracy:78,mobility:74,reliability:86},requirements:["унифицированная платформа","совместимый оптический интерфейс","устойчивость к интенсивной эксплуатации"],reward:1850,advance:500,penalty:650,durationHours:48,risk:"Перехват груза конкурентами и проверка происхождения партии.",difficulty:"MEDIUM",linkedMission:"valenti_04"},
{id:"nightglass",code:"N-04",title:"Контракт «Ночное стекло»",client:"Частная охранная группа «Меридиан»",lore:"Группа работает в плотной городской застройке и требует компактное оружие для патрульных групп.",weaponType:"Компактный карабин",caliber:"5.56×45 мм",spec:{damage:66,accuracy:82,mobility:88,reliability:80},requirements:["короткая конфигурация","низкая масса","модульный интерфейс"],reward:1600,advance:420,penalty:560,durationHours:36,risk:"Проверка на контрафактные комплектующие.",difficulty:"MEDIUM",linkedMission:"moretti_03"},
{id:"blackwaterline",code:"B-21",title:"Контракт «Чёрная линия»",client:"Группа «Северный порт»",lore:"Ночью пропали две партии оборудования. Заказчик меняет требования: груз должен быть компактным и устойчивым к грубой транспортировке.",weaponType:"Пистолет-пулемёт",caliber:"9×19 мм",spec:{damage:54,accuracy:68,mobility:94,reliability:84},requirements:["компактность","высокая мобильность","быстрая смена магазина"],reward:1320,advance:360,penalty:480,durationHours:30,risk:"Засада на маршруте и потеря части груза.",difficulty:"MEDIUM",linkedMission:"rossi_02"},
{id:"ironroute",code:"I-31",title:"Контракт «Железный маршрут»",client:"Логистический синдикат «Транзит»",lore:"Синдикат восстанавливает старый маршрут через промышленный район. Требуется надёжное оружие сопровождения.",weaponType:"Карабин",caliber:"7.62×39 мм",spec:{damage:84,accuracy:70,mobility:62,reliability:92},requirements:["высокая надёжность","простое обслуживание","устойчивость к загрязнению"],reward:2100,advance:600,penalty:780,durationHours:60,risk:"Блокирование маршрута и повреждение транспортной колонны.",difficulty:"HARD",linkedMission:"bellini_06"},
{id:"silent_district",code:"S-09",title:"Контракт «Тихий квартал»",client:"Корпоративная служба «Атлас»",lore:"Заказчику нужна малозаметная экипировка для вымышленной игровой операции наблюдения в городе.",weaponType:"Компактный пистолет",caliber:"9×19 мм",spec:{damage:48,accuracy:86,mobility:96,reliability:78},requirements:["скрытое ношение","низкая масса","стабильная точность"],reward:1180,advance:300,penalty:420,durationHours:24,risk:"Обнаружение наблюдательной группы.",difficulty:"EASY",linkedMission:"valenti_02"},
{id:"old_guard",code:"G-44",title:"Тендер «Старая гвардия»",client:"Охранная компания «Бастион»",lore:"«Бастион» заменяет устаревший парк оружия, но сохраняет приоритет надёжности и простоты эксплуатации.",weaponType:"Служебный пистолет",caliber:"9×19 мм",spec:{damage:58,accuracy:76,mobility:82,reliability:90},requirements:["простая эксплуатация","надёжность","единый тип боеприпаса"],reward:980,advance:240,penalty:320,durationHours:20,risk:"Конкурирующая заявка с демпингом.",difficulty:"EASY",linkedMission:"moretti_02"},
{id:"redarchive",code:"A-77",title:"Тендер «Красный архив»",client:"Закрытая аналитическая сеть «Архив»",lore:"Сеть формирует защищённую группу сопровождения для поиска потерянных документов.",weaponType:"Марксманский карабин",caliber:"7.62×51 мм",spec:{damage:92,accuracy:94,mobility:42,reliability:82},requirements:["высокая точность","стабильная оптика","контроль отдачи"],reward:2800,advance:800,penalty:1100,durationHours:72,risk:"Контрнаблюдение и потеря маршрута.",difficulty:"HARD",linkedMission:"rossi_08"},
{id:"fourfamilies",code:"F-13",title:"Контракт «Четыре печати»",client:"Совместный совет четырёх семей",lore:"После серии взаимных конфликтов стороны заключают временное соглашение. Нужна смешанная поставка для последней операции главы.",weaponType:"Смешанный оружейный комплект",caliber:"5.56×45 / 9×19 мм",spec:{damage:80,accuracy:84,mobility:76,reliability:88},requirements:["единый стандарт учёта","смешанная комплектация","полная проверка партии"],reward:4200,advance:1200,penalty:1800,durationHours:96,risk:"Срыв сделки одной из сторон и потеря доверия.",difficulty:"ELITE",linkedMission:"joint_13"}
];
export function tenderById(id:string){return TENDERS.find(t=>t.id===id)||null;}
export function difficultyRu(d:TenderDifficulty){return ({EASY:"НИЗКИЙ",MEDIUM:"СРЕДНИЙ",HARD:"ВЫСОКИЙ",ELITE:"ЭЛИТНЫЙ"} as Record<TenderDifficulty,string>)[d];}

export interface ArenaMission{ id:string; tenderId:string; order:number; title:string; briefing:string; objective:"clear"|"survive"|"reach"|"recover"|"defend"; target:number; reward:number; enemies:Array<"guard"|"brawler"|"heavy"|"rusher"|"shooter"|"sniper"|"suppressor"|"flanker">; arenaRule:string; }

// Одна арена. Каждый тендер проходит через последовательность отдельных боевых задач.
export const ARENA_MISSIONS:ArenaMission[]=[
{id:"R17-01",tenderId:"storm_rust",order:1,title:"КОНТАКТ НА ПЕРИМЕТРЕ",briefing:"Чужая группа вошла в сектор поставки. Периметр нужно очистить.",objective:"clear",target:8,reward:420,enemies:["guard","shooter","rusher"],arenaRule:"ПЕРИМЕТР"},
{id:"R17-02",tenderId:"storm_rust",order:2,title:"УЗЕЛ СВЯЗИ",briefing:"Связь группы подавлена. Удерживай узел, пока канал не восстановится.",objective:"survive",target:30,reward:520,enemies:["shooter","suppressor","flanker"],arenaRule:"УДЕРЖАНИЕ"},
{id:"R17-03",tenderId:"storm_rust",order:3,title:"ПОСЛЕДНИЙ ГРУЗ",briefing:"Последняя партия должна пройти через квартал. Не дай противнику сорвать маршрут.",objective:"defend",target:12,reward:720,enemies:["heavy","rusher","shooter","flanker"],arenaRule:"КОНВОЙ"},
{id:"N04-01",tenderId:"nightglass",order:1,title:"ТИХИЙ ПАТРУЛЬ",briefing:"Патрульная группа потеряла контроль над двором.",objective:"clear",target:7,reward:360,enemies:["guard","flanker","rusher"],arenaRule:"ДВОР"},
{id:"N04-02",tenderId:"nightglass",order:2,title:"СЛЕПОЙ УГОЛ",briefing:"Противник использует обходы. Удерживай позицию и переживи засаду.",objective:"survive",target:35,reward:480,enemies:["flanker","shooter","sniper"],arenaRule:"ЗАСАДА"},
{id:"N04-03",tenderId:"nightglass",order:3,title:"НОЧНОЙ ВЫХОД",briefing:"Найди выход из сектора, пока группа прикрытия держит противника.",objective:"reach",target:1,reward:620,enemies:["rusher","shooter","heavy"],arenaRule:"ПРОРЫВ"},
{id:"B21-01",tenderId:"blackwaterline",order:1,title:"ПРОПАВШАЯ ПАРТИЯ",briefing:"След груза обнаружен на улице. Верни контроль над зоной.",objective:"clear",target:9,reward:340,enemies:["rusher","guard","shooter"],arenaRule:"ПЕРЕХВАТ"},
{id:"B21-02",tenderId:"blackwaterline",order:2,title:"КОНТЕЙНЕРНЫЙ ДВОР",briefing:"Противник закрепился между контейнерами. Волны будут усиливаться.",objective:"survive",target:40,reward:460,enemies:["rusher","flanker","suppressor"],arenaRule:"КОНТЕЙНЕРЫ"},
{id:"B21-03",tenderId:"blackwaterline",order:3,title:"ПОСЛЕДНИЙ МАРШРУТ",briefing:"Пройди через сектор до контрольной точки.",objective:"reach",target:1,reward:600,enemies:["shooter","sniper","rusher","heavy"],arenaRule:"МАРШРУТ"},
{id:"I31-01",tenderId:"ironroute",order:1,title:"ЖЕЛЕЗНАЯ ЛИНИЯ",briefing:"Маршрут перекрыт. Уничтожь блокирующую группу.",objective:"clear",target:10,reward:520,enemies:["heavy","guard","rusher"],arenaRule:"БЛОКАДА"},
{id:"I31-02",tenderId:"ironroute",order:2,title:"ГРЯЗНЫЙ УЧАСТОК",briefing:"Противник атакует с нескольких направлений.",objective:"survive",target:45,reward:650,enemies:["heavy","suppressor","flanker","shooter"],arenaRule:"ИЗНОС"},
{id:"I31-03",tenderId:"ironroute",order:3,title:"СОПРОВОЖДЕНИЕ",briefing:"Удерживай контрольный коридор до завершения прохода.",objective:"defend",target:15,reward:900,enemies:["heavy","rusher","sniper","suppressor"],arenaRule:"КОЛОННА"},
{id:"S09-01",tenderId:"silent_district",order:1,title:"СЛЕПОЕ НАБЛЮДЕНИЕ",briefing:"Найди наблюдателей, не дав им окружить сектор.",objective:"clear",target:6,reward:300,enemies:["flanker","guard","sniper"],arenaRule:"НАБЛЮДЕНИЕ"},
{id:"S09-02",tenderId:"silent_district",order:2,title:"ТИХИЙ ДВОР",briefing:"Переживи короткую, но плотную атаку.",objective:"survive",target:25,reward:380,enemies:["flanker","rusher","shooter"],arenaRule:"СКРЫТНОСТЬ"},
{id:"S09-03",tenderId:"silent_district",order:3,title:"ЭКСТРАКЦИЯ",briefing:"Доберись до точки выхода.",objective:"reach",target:1,reward:500,enemies:["sniper","flanker","rusher"],arenaRule:"ЭВАКУАЦИЯ"},
{id:"G44-01",tenderId:"old_guard",order:1,title:"СМЕНА",briefing:"Старая охрана потеряла участок. Верни его.",objective:"clear",target:7,reward:260,enemies:["guard","brawler","rusher"],arenaRule:"СМЕНА"},
{id:"G44-02",tenderId:"old_guard",order:2,title:"ЗАПЕРТАЯ ДВЕРЬ",briefing:"Группа давит на вход. Удерживай позицию.",objective:"defend",target:10,reward:340,enemies:["guard","shooter","heavy"],arenaRule:"ВОРОТА"},
{id:"G44-03",tenderId:"old_guard",order:3,title:"ПОСЛЕДНИЙ ПОСТ",briefing:"Заверши зачистку участка.",objective:"clear",target:12,reward:520,enemies:["heavy","shooter","rusher","guard"],arenaRule:"ЗАЧИСТКА"},
{id:"A77-01",tenderId:"redarchive",order:1,title:"АРХИВНАЯ ОХРАНА",briefing:"Архив заблокирован вооружённой группой.",objective:"clear",target:10,reward:600,enemies:["guard","shooter","heavy"],arenaRule:"АРХИВ"},
{id:"A77-02",tenderId:"redarchive",order:2,title:"КОНТРНАБЛЮДЕНИЕ",briefing:"Снайперы и обходчики перекрывают сектор.",objective:"survive",target:50,reward:760,enemies:["sniper","flanker","suppressor","heavy"],arenaRule:"КОНТРНАБЛЮДЕНИЕ"},
{id:"A77-03",tenderId:"redarchive",order:3,title:"КРАСНЫЙ ФАЙЛ",briefing:"Забери файл и выйди из сектора.",objective:"recover",target:1,reward:1100,enemies:["sniper","heavy","shooter","flanker"],arenaRule:"ИЗВЛЕЧЕНИЕ"},
{id:"F13-01",tenderId:"fourfamilies",order:1,title:"ЧЕТЫРЕ СЕКТОРА",briefing:"Все четыре стороны прислали свои группы. Удержи арену.",objective:"clear",target:14,reward:800,enemies:["guard","rusher","shooter","flanker"],arenaRule:"ЧЕТЫРЕ СЕКТОРА"},
{id:"F13-02",tenderId:"fourfamilies",order:2,title:"РАЗРЫВ",briefing:"Союз трещит. Тяжёлые группы атакуют по очереди.",objective:"survive",target:60,reward:1100,enemies:["heavy","suppressor","sniper","rusher"],arenaRule:"РАЗРЫВ"},
{id:"F13-03",tenderId:"fourfamilies",order:3,title:"ПОСЛЕДНЯЯ ПЕЧАТЬ",briefing:"Последний узел должен быть удержан до конца операции.",objective:"defend",target:20,reward:1600,enemies:["heavy","suppressor","sniper","flanker","shooter"],arenaRule:"ФИНАЛ"}
];
export function arenaMissionsForTender(id:string){return ARENA_MISSIONS.filter(m=>m.tenderId===id).sort((a,b)=>a.order-b.order);}
