export type GameRace="human"|"elf"|"orc"|"dwarf";
export type GameTab="story"|"character"|"skills"|"achievements"|"journal";
export interface GameState{race:GameRace|null;level:number;xp:number;step:number;health:number;energy:number;stats:{strength:number;endurance:number;mind:number;awareness:number;influence:number};skills:{exploration:number;negotiation:number;survival:number;knowledge:number;observation:number;will:number};reputation:{human:number;elf:number;orc:number;dwarf:number};achievements:string[];known:string[];promises:string[];choices:string[]}
const KEY="freezzz:game-state:v2";
const RACES:Record<GameRace,{name:string;icon:string;description:string;stats:GameState["stats"]}>={
 human:{name:"Человек",icon:"○",description:"Гибкий старт. Люди легче приспосабливаются к чужим обычаям.",stats:{strength:5,endurance:5,mind:5,awareness:5,influence:6}},
 elf:{name:"Эльф",icon:"✧",description:"Тонкое восприятие и природная связь с миром.",stats:{strength:4,endurance:4,mind:7,awareness:7,influence:5}},
 orc:{name:"Орк",icon:"◇",description:"Выносливость и прямой характер. Доверие мира нужно заслужить.",stats:{strength:8,endurance:7,mind:3,awareness:5,influence:3}},
 dwarf:{name:"Гном",icon:"△",description:"Практичный ум, крепкий характер и любовь к тайнам старых мест.",stats:{strength:6,endurance:7,mind:7,awareness:4,influence:4}}
};
const DEFAULT_STATE:GameState={race:null,level:1,xp:0,step:1,health:72,energy:60,stats:{strength:5,endurance:5,mind:5,awareness:5,influence:5},skills:{exploration:0,negotiation:0,survival:0,knowledge:0,observation:0,will:0},reputation:{human:50,elf:0,orc:0,dwarf:0},achievements:[],known:[],promises:[],choices:[]};
export function loadGameState():GameState{try{const raw=localStorage.getItem(KEY);if(!raw)return structuredClone(DEFAULT_STATE);const p=JSON.parse(raw) as Partial<GameState>;return {...structuredClone(DEFAULT_STATE),...p,stats:{...DEFAULT_STATE.stats,...p.stats},skills:{...DEFAULT_STATE.skills,...p.skills},reputation:{...DEFAULT_STATE.reputation,...p.reputation}}}catch{return structuredClone(DEFAULT_STATE)}}
export function saveGameState(s:GameState){try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}}
export function restartGame():GameState{const n=structuredClone(DEFAULT_STATE);try{localStorage.removeItem(KEY)}catch{}return n}
export function chooseRace(s:GameState,r:GameRace):GameState{const base=RACES[r];const n={...s,race:r,stats:{...base.stats},step:1,level:1,xp:0};n.reputation={...s.reputation,[r]:60};saveGameState(n);return n}
export function raceInfo(r:GameRace){return RACES[r]}
const SKILLS=[
 ["exploration","Исследование","◇"],
 ["negotiation","Переговоры","◫"],
 ["survival","Выживание","✦"],
 ["knowledge","Знания","▤"],
 ["observation","Наблюдение","◉"],
 ["will","Воля","◇"]
] as const;
export function gameSkills(){return SKILLS}
function bars(s:GameState){return [["Сила","✦",s.stats.strength],["Выносливость","○",s.stats.endurance],["Разум","◇",s.stats.mind],["Внимание","◉",s.stats.awareness],["Влияние","●",s.stats.influence]].map(x=>'<div class="game-stat"><span><i>'+x[1]+'</i>'+x[0]+'</span><b>'+x[2]+'</b><em><u style="width:'+Math.min(100,(x[2] as number)*10)+'%"></u></em></div>').join("")}
function tabs(t:GameTab){return [["story","▤"],["character","○"],["skills","✦"],["achievements","◆"],["journal","▤"]].map(x=>'<button class="'+(t===x[0]?"active":"")+'" data-game-tab="'+x[0]+'" type="button">'+x[1]+'</button>').join("")}
function racePicker(){return '<div class="game-rpg game-race-picker"><div class="game-intro"><span>FREEzzz STORY · CHAPTER 01</span><h2>КТО ТЫ?</h2><p>Выбери происхождение героя. Оно меняет стартовые характеристики и некоторые реакции мира.</p></div><div class="race-grid">'+(Object.keys(RACES) as GameRace[]).map(r=>{const x=RACES[r];return '<button class="race-card" data-game-race="'+r+'" type="button"><span>'+x.icon+'</span><strong>'+x.name+'</strong><small>'+x.description+'</small><em>Сила '+x.stats.strength+' · Разум '+x.stats.mind+' · Внимание '+x.stats.awareness+'</em></button>'}).join("")+'</div></div>'}
function story(s:GameState,r:{name:string;icon:string}){const first=s.step===1;const text=first?"Ночь была слишком тихой. За лесом начинался путь к старой границе, а у костра оставалось слишком много вопросов.":"Костёр почти погас. Следы на влажной земле ведут к старой тропе, но впереди можно выбрать свой путь.";const thought=first?"Я — "+r.name+". Сегодня начинается история, которую никто не сможет пройти за меня.":"Я уже сделал первый шаг. Теперь важно понять, чему научиться дальше.";const choices=first?'<button data-game-choice="explore" type="button"><b>①</b> Исследовать старую тропу</button><button data-game-choice="elder" type="button"><b>②</b> Поговорить со старейшиной</button><button data-game-choice="fire" type="button"><b>③</b> Подготовить лагерь к дороге</button>':'<button data-game-choice="follow" type="button"><b>①</b> Следовать по следам</button><button data-game-choice="listen" type="button"><b>②</b> Остановиться и прислушаться</button><button data-game-choice="return" type="button"><b>③</b> Вернуться к поселению';return '<section class="game-story"><div class="game-scene"><div class="scene-stars">✦ · ✦ · · ✦</div><div class="scene-moon">◐</div><div class="scene-fire">♨</div><div class="scene-silhouette">♟</div><small>НОЧЬ · СТАРАЯ ОПУШКА</small></div><article class="game-dialog"><span class="game-speaker">'+(first?"ВНУТРЕННИЙ ГОЛОС":"АЙВАР")+'</span><p>'+text+'</p><span class="game-speaker">ВЫ</span><p class="game-thought">'+thought+'</p></article><div class="game-choices">'+choices+'</div></section>'}
export function renderGame(s:GameState,t:GameTab):string{if(!s.race)return racePicker();const r=RACES[s.race];let p="";if(t==="story")p=story(s,r);if(t==="character")p='<section class="game-panel"><div class="game-panel-title"><span>ХАРАКТЕРИСТИКИ</span><small>LVL '+s.level+' · XP '+s.xp+'/100</small></div>'+bars(s)+'</section>';if(t==="skills")p='<section class="game-panel"><div class="game-panel-title"><span>НАВЫКИ</span><small>Растут через решения</small></div>'+SKILLS.map(x=>'<div class="game-skill"><span>'+x[2]+' '+x[1]+'</span><b>'+s.skills[x[0]]+'</b><em><u style="width:'+Math.min(100,s.skills[x[0]]*20)+'%"></u></em></div>').join("")+'</section>';if(t==="achievements")p='<section class="game-panel"><div class="game-panel-title"><span>АЧИВКИ</span><small>'+s.achievements.length+' открыто</small></div>'+((s.achievements.length?s.achievements:["Первый шаг","???","???"]).map(a=>'<div class="game-achievement '+(a==="???"?"locked":"")+'"><span>'+(a==="???"?"?":"◆")+'</span><div><b>'+a+'</b><small>'+(a==="???"?"Скрытое достижение":"Получено по ходу истории")+'</small></div></div>').join(""))+'</section>';if(t==="journal")p='<section class="game-panel"><div class="game-panel-title"><span>ЖУРНАЛ</span><small>Глава '+s.step+'</small></div><div class="game-journal"><b>Известно</b>'+((s.known.length?s.known:["История только начинается."]).map(x=>'<p>✓ '+x+'</p>').join(""))+'<b>Обещания</b>'+((s.promises.length?s.promises:["Пока нет."]).map(x=>'<p>○ '+x+'</p>').join(""))+'</div></section>';return '<div class="game-rpg" data-game-root><header class="game-player-head"><div class="game-avatar">'+r.icon+'</div><div><strong>Айвар</strong><small>'+r.name+' · Уровень '+s.level+'</small></div><div class="game-vitals"><span>♥ '+s.health+'</span><span>⚡ '+s.energy+'</span><button class="game-restart" data-game-restart type="button">Новая игра</button></div></header><nav class="game-tabs">'+tabs(t)+'</nav>'+p+'</div>'}
export function applyGameChoice(s:GameState,c:string):GameState{const n={...s,choices:[...s.choices,c],known:[...s.known],promises:[...s.promises],skills:{...s.skills},stats:{...s.stats},achievements:[...s.achievements]};if(c==="explore"||c==="follow"){n.skills.exploration=Math.max(n.skills.exploration,c==="follow"?n.skills.exploration+1:1);n.skills.observation=Math.max(n.skills.observation,1);n.known.push("Старая тропа ведёт к границе.");}if(c==="elder"){n.skills.negotiation=Math.max(n.skills.negotiation,1);n.known.push("Старейшина знает о старой границе.");n.promises.push("Вернуться с новостями о тропе.");}if(c==="fire"){n.skills.survival=Math.max(n.skills.survival,1);n.energy=Math.min(100,n.energy+8);n.known.push("Подготовленный лагерь экономит силы.");}if(c==="listen"){n.skills.observation++;n.skills.will++;}if(c==="return"){n.skills.negotiation++;n.energy=Math.min(100,n.energy+5);}if(!n.achievements.includes("Первый шаг"))n.achievements.push("Первый шаг");n.xp+=20;if(n.xp>=100){n.level++;n.xp-=100;n.achievements.push("Новый уровень")}n.step=Math.min(100,n.step+1);saveGameState(n);return n}
