export type GameRace="human"|"elf"|"orc"|"dwarf";
export type GameTab="story"|"character"|"skills"|"achievements"|"journal";
export interface GameState{race:GameRace|null;level:number;xp:number;step:number;health:number;energy:number;stats:{strength:number;endurance:number;mind:number;awareness:number;influence:number};skills:{combat:number;marksmanship:number;negotiation:number;survival:number;magic:number;scouting:number};reputation:{human:number;elf:number;orc:number;dwarf:number};achievements:string[];known:string[];promises:string[];choices:string[]}
const KEY="freezzz:game-state:v1";
const RACES:Record<GameRace,{name:string;icon:string;description:string;stats:GameState["stats"]}>={human:{name:"Человек",icon:"👤",description:"Гибкий старт. Люди легче приспосабливаются к чужим обычаям.",stats:{strength:5,endurance:5,mind:5,awareness:5,influence:6}},elf:{name:"Эльф",icon:"🧝",description:"Тонкое восприятие и природная связь с магией.",stats:{strength:4,endurance:4,mind:7,awareness:7,influence:5}},orc:{name:"Орк",icon:"🪓",description:"Выносливость и сила. С чужим доверием придётся работать.",stats:{strength:8,endurance:7,mind:3,awareness:5,influence:3}},dwarf:{name:"Гном",icon:"⛏️",description:"Практичный ум и крепкий характер.",stats:{strength:6,endurance:7,mind:7,awareness:4,influence:4}}};
const DEFAULT_STATE:GameState={race:null,level:1,xp:0,step:1,health:72,energy:41,stats:{strength:5,endurance:5,mind:5,awareness:5,influence:5},skills:{combat:0,marksmanship:0,negotiation:0,survival:0,magic:0,scouting:0},reputation:{human:50,elf:0,orc:0,dwarf:0},achievements:[],known:[],promises:[],choices:[]};
export function loadGameState():GameState{try{const raw=localStorage.getItem(KEY);if(!raw)return structuredClone(DEFAULT_STATE);const p=JSON.parse(raw) as GameState;return {...structuredClone(DEFAULT_STATE),...p,stats:{...DEFAULT_STATE.stats,...p.stats},skills:{...DEFAULT_STATE.skills,...p.skills},reputation:{...DEFAULT_STATE.reputation,...p.reputation}}}catch{return structuredClone(DEFAULT_STATE)}}
export function saveGameState(s:GameState){try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}}
export function chooseRace(s:GameState,r:GameRace):GameState{const b=RACES[r];const n={...s,race:r,stats:{...b.stats},step:1,level:1,xp:0};n.reputation[r]=60;saveGameState(n);return n}
export function raceInfo(r:GameRace){return RACES[r]}
const SKILLS=[["combat","Бой","⚔"],["marksmanship","Меткость","🏹"],["negotiation","Переговоры","🗣"],["survival","Выживание","🌲"],["magic","Магия","✦"],["scouting","Разведка","👁"]] as const;
export function gameSkills(){return SKILLS}
function bars(s:GameState){return [["Сила","⚔",s.stats.strength],["Выносливость","🛡",s.stats.endurance],["Разум","🧠",s.stats.mind],["Внимание","👁",s.stats.awareness],["Влияние","🗣",s.stats.influence]].map(x=>'<div class="game-stat"><span><i>'+x[1]+'</i>'+x[0]+'</span><b>'+x[2]+'</b><em><u style="width:'+Math.min(100,(x[2] as number)*10)+'%"></u></em></div>').join("")}
function tabs(t:GameTab){return [["story","📖"],["character","👤"],["skills","⚔"],["achievements","◆"],["journal","▤"]].map(x=>'<button class="'+(t===x[0]?"active":"")+'" data-game-tab="'+x[0]+'" type="button">'+x[1]+'</button>').join("")}
function racePicker(){return '<div class="game-rpg game-race-picker"><div class="game-intro"><span>FREEzzz STORY · 01</span><h2>КТО ТЫ?</h2><p>Раса меняет стартовые характеристики, реакции мира и доступные варианты.</p></div><div class="race-grid">'+(Object.keys(RACES) as GameRace[]).map(r=>{const x=RACES[r];return '<button class="race-card" data-game-race="'+r+'" type="button"><span>'+x.icon+'</span><strong>'+x.name+'</strong><small>'+x.description+'</small><em>Сила '+x.stats.strength+' · Разум '+x.stats.mind+' · Внимание '+x.stats.awareness+'</em></button>'}).join("")+'</div></div>'}
function story(s:GameState,r:{name:string;icon:string}){const first=s.step===1;return '<section class="game-story"><div class="game-scene"><div class="scene-stars">✦ · · ✦</div><div class="scene-moon">◐</div><div class="scene-fire">🔥</div><div class="scene-silhouette">♟</div><small>НОЧЬ · ЛЕСНАЯ ОПУШКА</small></div><article class="game-dialog"><span class="game-speaker">'+(first?"ВНУТРЕННИЙ ГОЛОС":"АЙВАР")+'</span><p>'+(first?"Ночь была слишком тихой. Обычно тишина ничего не обещает. Эта — обещала неприятности.":"Костёр догорал. Где-то за деревьями хрустнула ветка, и лес вдруг перестал казаться пустым.")+'</p><span class="game-speaker">ВЫ</span><p class="game-thought">'+(first?"Я — "+r.name+". Остальное ещё предстоит выяснить.":"Если неприятности уже пришли, делать вид, что их нет, обычно поздно.")+'</p></article><div class="game-choices">'+(first?'<button data-game-choice="shadow" type="button"><b>①</b> Идти с оружием в тень</button><button data-game-choice="elder" type="button"><b>②</b> Разбудить старейшину</button><button data-game-choice="fire" type="button"><b>③</b> Подбросить дров в костёр</button>':'<button data-game-choice="search" type="button"><b>①</b> Проверить лес</button><button data-game-choice="wait" type="button"><b>②</b> Остаться у костра</button>')+'</div></section>'}
export function renderGame(s:GameState,t:GameTab):string{if(!s.race)return racePicker();const r=RACES[s.race];let p="";if(t==="story")p=story(s,r);if(t==="character")p='<section class="game-panel"><div class="game-panel-title"><span>ХАРАКТЕРИСТИКИ</span><small>LVL '+s.level+'</small></div>'+bars(s)+'</section>';if(t==="skills")p='<section class="game-panel"><div class="game-panel-title"><span>НАВЫКИ</span><small>Развиваются через действия</small></div>'+SKILLS.map(x=>'<div class="game-skill"><span>'+x[2]+' '+x[1]+'</span><b>'+s.skills[x[0]]+'</b><em><u style="width:'+Math.min(100,s.skills[x[0]]*20)+'%"></u></em></div>').join("")+'</section>';if(t==="achievements")p='<section class="game-panel"><div class="game-panel-title"><span>АЧИВКИ</span><small>'+s.achievements.length+' открыто</small></div>'+((s.achievements.length?s.achievements:["???","???","???"]).map(a=>'<div class="game-achievement '+(a==="???"?"locked":"")+'"><span>'+(a==="???"?"?":"◆")+'</span><div><b>'+a+'</b><small>'+(a==="???"?"Скрытое достижение":"Получено по ходу истории")+'</small></div></div>').join(""))+'</section>';if(t==="journal")p='<section class="game-panel"><div class="game-panel-title"><span>ЖУРНАЛ</span><small>Шаг '+s.step+'/100</small></div><div class="game-journal"><b>Известно</b>'+((s.known.length?s.known:["История только начинается."]).map(x=>'<p>✓ '+x+'</p>').join(""))+'<b>Обещания</b>'+((s.promises.length?s.promises:["Пока нет."]).map(x=>'<p>○ '+x+'</p>').join(""))+'</div></section>';return '<div class="game-rpg" data-game-root><header class="game-player-head"><div class="game-avatar">'+r.icon+'</div><div><strong>Айвар</strong><small>'+r.name+' · Уровень '+s.level+'</small></div><div class="game-vitals"><span>♥ '+s.health+'</span><span>⚡ '+s.energy+'</span></div></header><nav class="game-tabs">'+tabs(t)+'</nav>'+p+'</div>'}
export function applyGameChoice(s:GameState,c:string):GameState{const n={...s,choices:[...s.choices,c],known:[...s.known],promises:[...s.promises],skills:{...s.skills}};if(c==="shadow"){n.skills.scouting=Math.max(n.skills.scouting,1);n.known.push("В лесу есть кто-то ещё.")}if(c==="elder"){n.skills.negotiation=Math.max(n.skills.negotiation,1);n.promises.push("Выяснить, что происходит у границы.")}if(c==="fire"){n.skills.survival=Math.max(n.skills.survival,1);n.energy=Math.min(100,n.energy+4)}if(c==="search")n.skills.scouting++;if(c==="wait")n.stats.awareness++;n.xp+=10;if(n.xp>=100){n.level++;n.xp=0}n.step=Math.min(100,n.step+1);saveGameState(n);return n}